const ACTION_TYPES = {
    EXPENSES_LOADING: 'EXPENSES_LOADING',
    GET_EXPENSES: 'GET_EXPENSES',
    ADD_EXPENSES: 'ADD_EXPENSES',
    DELETE_EXPENSES: 'DELETE_EXPENSES'
}

export default ACTION_TYPES;